# Generated by Django 5.0.6 on 2024-08-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_created_by_alter_person_room_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
    ]
