# Generated by Django 5.0.6 on 2024-08-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_table_alter_room_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='charged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
