# Generated by Django 5.0.6 on 2024-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_balance_person_charged_person_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='charged',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
