# Generated by Django 5.0.6 on 2024-08-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_person_balance_alter_person_charged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
                ('who_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_paid', to='main.person')),
            ],
            options={
                'db_table': 'TransactionDetail',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='persons',
            field=models.ManyToManyField(through='main.TransactionDetail', to='main.person'),
        ),
    ]
